{
 "title": "Many nods",
 "tags": [ "linux" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_01\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_01\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_01\"}) by (cpu))",
     "legendFormat": "contabo_01"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_02\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_02\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_02\"}) by (cpu))",
     "legendFormat": "contabo_02"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_03\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_03\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_03\"}) by (cpu))",
     "legendFormat": "contabo_03"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_04\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_04\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_04\"}) by (cpu))",
     "legendFormat": "contabo_04"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_05\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_05\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_05\"}) by (cpu))",
     "legendFormat": "contabo_05"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_06\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_06\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_06\"}) by (cpu))",
     "legendFormat": "contabo_06"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_07\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_07\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_07\"}) by (cpu))",
     "legendFormat": "contabo_07"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_08\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_08\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_08\"}) by (cpu))",
     "legendFormat": "contabo_08"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_09\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_09\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_09\"}) by (cpu))",
     "legendFormat": "contabo_09"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_10\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_10\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_10\"}) by (cpu))",
     "legendFormat": "contabo_10"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_11\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_11\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_11\"}) by (cpu))",
     "legendFormat": "contabo_11"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"contabo_12\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"contabo_12\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"contabo_12\"}) by (cpu))",
     "legendFormat": "contabo_12"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_01\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_01\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_01"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_02\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_02\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_02"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_03\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_03\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_03"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_04\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_04\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_04"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_05\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_05\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_05"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_06\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_06\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_06"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_07\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_07\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_07"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_08\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_08\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_08"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_09\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_09\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_09"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_10\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_10\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_10"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_11\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_11\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_11"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"contabo_12\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"contabo_12\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "contabo_12"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_01\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_01\"})",
     "legendFormat": "contabo_01"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_02\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_02\"})",
     "legendFormat": "contabo_02"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_03\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_03\"})",
     "legendFormat": "contabo_03"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_04\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_04\"})",
     "legendFormat": "contabo_04"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_05\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_05\"})",
     "legendFormat": "contabo_05"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_06\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_06\"})",
     "legendFormat": "contabo_06"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_07\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_07\"})",
     "legendFormat": "contabo_07"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_08\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_08\"})",
     "legendFormat": "contabo_08"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_09\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_09\"})",
     "legendFormat": "contabo_09"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_10\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_10\"})",
     "legendFormat": "contabo_10"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_11\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_11\"})",
     "legendFormat": "contabo_11"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"contabo_12\"} * 100) / node_memory_MemTotal_bytes{job=\"contabo_12\"})",
     "legendFormat": "contabo_12"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}